// <auto-generated />
using System;
using MBC.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MBC.Persistence.Migrations
{
    [DbContext(typeof(MBCDbContext))]
    partial class MBCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MBC.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Nickname")
                        .IsRequired()
                        ;

                    b.Property<Guid>("UserId")
                        ;

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MBC.Core.Entities.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime?>("CompletedOn")
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CustomerId")
                        ;

                    b.Property<Guid?>("DestinationId")
                        ;

                    b.Property<Guid?>("OriginId")
                        ;

                    b.Property<Guid>("PaymentId")
                        ;

                    b.Property<Guid>("PilotId")
                        ;

                    b.Property<int>("Status")
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.HasIndex("PilotId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("MBC.Core.Entities.DeliveryProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CustomerId")
                        ;

                    b.Property<Guid>("DeliveryId")
                        ;

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        ;

                    b.Property<Guid>("PilotId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryId")
                        .IsUnique();

                    b.HasIndex("PilotId");

                    b.ToTable("DeliveryProofs");
                });

            modelBuilder.Entity("MBC.Core.Entities.DeliveryReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("CustomerId")
                        ;

                    b.Property<Guid>("DeliveryId")
                        ;

                    b.Property<string>("Notes")
                        .IsRequired()
                        ;

                    b.Property<Guid>("PilotId")
                        ;

                    b.Property<int>("Rating")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryId")
                        .IsUnique();

                    b.HasIndex("PilotId");

                    b.ToTable("DeliveryReviews");
                });

            modelBuilder.Entity("MBC.Core.Entities.MBCUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("AccessFailedCount")
                        ;

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        ;

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        ;

                    b.Property<bool>("EmailConfirmed")
                        ;

                    b.Property<bool>("LockoutEnabled")
                        ;

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        ;

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("PasswordHash")
                        ;

                    b.Property<string>("PhoneNumber")
                        ;

                    b.Property<bool>("PhoneNumberConfirmed")
                        ;

                    b.Property<string>("SecurityStamp")
                        ;

                    b.Property<bool>("TwoFactorEnabled")
                        ;

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MBC.Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<Guid>("DeliveryId")
                        ;

                    b.Property<string>("MerchantReference")
                        .IsRequired()
                        ;

                    b.Property<int>("Status")
                        ;

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        ;

                    b.Property<DateTime>("UpdatedAt")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MBC.Core.Entities.Pilot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("AvatarUrl")
                        ;

                    b.Property<string>("Bio")
                        .IsRequired()
                        ;

                    b.Property<string>("FullName")
                        .IsRequired()
                        ;

                    b.Property<string>("ShortName")
                        .IsRequired()
                        ;

                    b.Property<Guid>("UserId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("MBC.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<DateTime?>("DeactivatedAt")
                        ;

                    b.Property<DateTime>("ExpiresAt")
                        ;

                    b.Property<Guid>("FamilyId")
                        ;

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        ;

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(450)
                        ;

                    b.Property<Guid>("UserId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MBC.Core.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Address")
                        .IsRequired()
                        ;

                    b.Property<string>("ImageUrl")
                        ;

                    b.Property<string>("Island")
                        .IsRequired()
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        ;

                    b.Property<string>("Notes")
                        .IsRequired()
                        ;

                    b.Property<int>("Status")
                        ;

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        ;

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ClaimType")
                        ;

                    b.Property<string>("ClaimValue")
                        ;

                    b.Property<Guid>("RoleId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ClaimType")
                        ;

                    b.Property<string>("ClaimValue")
                        ;

                    b.Property<Guid>("UserId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        ;

                    b.Property<string>("ProviderKey")
                        ;

                    b.Property<string>("ProviderDisplayName")
                        ;

                    b.Property<Guid>("UserId")
                        ;

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        ;

                    b.Property<Guid>("RoleId")
                        ;

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        ;

                    b.Property<string>("LoginProvider")
                        ;

                    b.Property<string>("Name")
                        ;

                    b.Property<string>("Value")
                        ;

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MBC.Core.Entities.Delivery", b =>
                {
                    b.HasOne("MBC.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBC.Core.Entities.Site", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.HasOne("MBC.Core.Entities.Site", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId");

                    b.HasOne("MBC.Core.Entities.Pilot", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MBC.Core.Models.JobDetails", "Details", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                ;

                            b1.Property<string>("CargoDescription")
                                .IsRequired()
                                ;

                            b1.Property<decimal>("CargoWeightKg")
                                .HasPrecision(18, 2)
                                ;

                            b1.Property<Guid>("DestinationId")
                                ;

                            b1.Property<Guid>("OriginId")
                                ;

                            b1.Property<DateOnly>("ScheduledFor")
                                ;

                            b1.HasKey("DeliveryId");

                            b1.ToTable("Deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("Destination");

                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("Origin");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("MBC.Core.Entities.DeliveryProof", b =>
                {
                    b.HasOne("MBC.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MBC.Core.Entities.Delivery", "Delivery")
                        .WithOne("Proof")
                        .HasForeignKey("MBC.Core.Entities.DeliveryProof", "DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBC.Core.Entities.Pilot", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Delivery");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("MBC.Core.Entities.DeliveryReview", b =>
                {
                    b.HasOne("MBC.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MBC.Core.Entities.Delivery", "Delivery")
                        .WithOne("Review")
                        .HasForeignKey("MBC.Core.Entities.DeliveryReview", "DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBC.Core.Entities.Pilot", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Delivery");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("MBC.Core.Entities.Payment", b =>
                {
                    b.HasOne("MBC.Core.Entities.Delivery", "Delivery")
                        .WithOne("Payment")
                        .HasForeignKey("MBC.Core.Entities.Payment", "DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MBC.Core.Models.CreditCardInfo", "CreditCard", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                ;

                            b1.Property<string>("CardNumber")
                                .IsRequired()
                                ;

                            b1.Property<string>("CardholderName")
                                .IsRequired()
                                ;

                            b1.Property<string>("Cvc")
                                .IsRequired()
                                ;

                            b1.Property<DateOnly>("Expiration")
                                ;

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("CreditCard")
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("MBC.Core.Entities.Site", b =>
                {
                    b.OwnsOne("MBC.Core.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("SiteId")
                                ;

                            b1.Property<byte>("X")
                                ;

                            b1.Property<byte>("Y")
                                ;

                            b1.HasKey("SiteId");

                            b1.ToTable("Sites");

                            b1.WithOwner()
                                .HasForeignKey("SiteId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MBC.Core.Entities.MBCUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MBC.Core.Entities.MBCUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBC.Core.Entities.MBCUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MBC.Core.Entities.MBCUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MBC.Core.Entities.Delivery", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Proof");

                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
